// src/routes/writing/+page.svelte
<script lang="ts">
	import ArrowRightIcon from 'phosphor-svelte/lib/ArrowRightIcon';

	interface Post {
		title: string;
		description: string;
		date: Date;
		link: string;
	}

	const posts: Post[] = [
		{
			title: 'Launching Developer Accelerator',
			description: 'Rebuilding my portfolio site',
			date: new Date('Feb 28, 2026'),
			link: 'launching-devx'
		},
		{
			title: 'Redesign 2026',
			description: 'Rebuilding my portfolio site',
			date: new Date('Feb 16, 2026'),
			link: 'redesign-2026'
		},
		{
			title: "AI's frontend",
			description: 'Why LLMs are so popular',
			date: new Date('April 16, 2025'),
			link: 'ai-frontend'
		},
		{
			title: 'Inspired by',
			description: 'Why you should copy people',
			date: new Date('April 29, 2025'),
			link: 'inspired-by'
		}
	];

	const postsByYear = $derived(
		posts.reduce<Record<number, Post[]>>((acc, post) => {
			const year = post.date.getFullYear();
			if (!acc[year]) acc[year] = [];
			acc[year].push(post);
			return acc;
		}, {})
	);

	const sortedYears = $derived(
		Object.keys(postsByYear)
			.map(Number)
			.sort((a, b) => b - a)
	);
</script>

<a
	href="/"
	class="col-start-1 grid h-fit w-full max-lg:mb-8 max-sm:col-span-12 sm:grid-flow-row md:row-span-2 lg:ml-8"
>
	Index
</a>
<section class="grid-centre flex flex-col gap-8">
	{#each sortedYears as year}
		<div class="flex max-xl:flex-col">
			<div class="col-start-1 w-[3em] pt-4 text-sm font-medium text-muted sm:w-[7em]">{year}</div>
			<div class="col-start-2 flex grow flex-col divide-y">
				{#each [...postsByYear[year]].sort((a, b) => b.date.getTime() - a.date.getTime()) as post}
					<a href={`/writing/${post.link}`} class="group flex items-center justify-between py-3">
						<div class="flex items-center transition-all duration-300 ease-out">
							<p class="font-medium">{post.title}</p>
							<ArrowRightIcon
								class="ml-2 size-4 -translate-x-2 text-cyan-600 opacity-0 transition-all delay-200 duration-150 ease-out group-hover:translate-x-0 group-hover:opacity-100 dark:text-cyan-400"
							/>
						</div>
						<time class="text-muted-foreground min-w-15 text-right text-sm">
							{post.date.toLocaleDateString('en-US', {
								day: 'numeric',
								month: 'short'
							})}
						</time>
					</a>
				{/each}
			</div>
		</div>
	{/each}
</section>

// src/app/writing/page.tsx
import Link from 'next/link';
import Header from '@/components/header';
import BackLink from '@/components/backlink';

interface Post {
  title: string
  description: string
  date: Date
  link: string
}

const posts: Post[] = [
  {
    title: "AI's frontend",
    description: 'Why LLMs are so popular',
    date: new Date('April 16, 2025'),
    link: 'ai-frontend'
  },
  {
    title: 'Inspired by',
    description: 'Why you should copy people',
    date: new Date('April 29, 2025'),
    link: 'inspired-by'
  },
  // {
  //   title: 'Focus',
  //   description: 'Becoming a master of one',
  //   date: new Date('July 1, 2025'),
  //   link: 'focus'
  // },
]

function Writing() {
  // Group posts by year
  const postsByYear = posts.reduce<Record<number, Post[]>>((acc, post) => {
    const year = post.date.getFullYear();
    if (!acc[year]) acc[year] = [];
    acc[year].push(post);
    return acc;
  }, {});

  // Sort years descending
  const sortedYears = Object.keys(postsByYear)
    .map(Number)
    .sort((a, b) => b - a);

  return (
    <>
      <BackLink link='/' text='Index' />
      <Header
        title='Writing'
        desc='Infrequent thoughts on software development'
      />
      <section className='grid sm:mt-8 mt-4 mb-[50dvh] divide-y border-t border-muted hover:text-muted-foreground/70'>
        {sortedYears.map((year) => (
          <div key={year} className="grid grid-cols-[auto,1fr]">
            <div className="text-muted-foreground font-medium w-[3em] sm:w-[7em] pt-4 text-sm">{year}</div>
            <div className="flex flex-col divide-y">
              {[...postsByYear[year]]
                .sort((a, b) => (b.date.getTime()) - (a.date.getTime()))
                .map((post, index) => (
                <Link
                  prefetch={true}
                  href={`/writing/${post.link}`}
                  key={index}
                  className="no-underline py-3 hover:no-underline hover:text-primary flex items-center justify-between"
                >
                  <div className="flex flex-col">
                    <p className="font-medium">{post.title}</p>
                    {/* {post.description && (
                      <p className="text-muted-foreground text-sm">{post.description}</p>
                    )} */}
                  </div>
                  <time className="text-muted-foreground text-sm min-w-[60px] text-right">
                    {post.date.toLocaleDateString('en-US', {
                      month: '2-digit',
                      day: '2-digit',
                    })}
                  </time>
                </Link>
              ))}
            </div>
          </div>
        ))}
      </section>
    </>
  )
}

export default Writing;
